[build]
  base = "sanity"
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  SECRETS_SCAN_SMART_DETECTION_ENABLED = "false"

# Frontend job pages
[[redirects]]
  from = "/jobs/:slug"
  to = "/jobs/:slug.html"
  status = 200

[[redirects]]
  from = "/bursary/:slug"
  to = "/bursary/:slug.html"
  status = 200



