[build]
  publish = "."
  command = ""

[[redirects]]
  from = "/jobs/:slug"
  to = "/jobs/[slug].html"
  status = 200
  force = true

[[redirects]]
  from = "/bursary/:slug"
  to = "/bursary/[slug].html"
  status = 200
  force = true


[build.environment]
  NODE_VERSION = "20"
  SECRETS_SCAN_SMART_DETECTION_ENABLED = "false"
